name: GenerateRelease
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS@v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      - name: Install Deps
        run: npm install
      - name: Build Project
        run: npx ng build book-reader-root --base-href=/reader/
      - name: Package Assets
        run: |
          zip -r /tmp/book-reader-web.zip ./dist/book-reader-root/browser
          tar -zcvf /tmp/book-reader-web.tar.gz ./dist/book-reader-root/browser
      - name: Copy Other Assets
        run: |
          cp ./CNAME ./dist/book-reader-root/browser/
          cp ./dist/book-reader-root/browser/index.html ./dist/book-reader-root/browser/404.html
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist/ghpages
          external_repository: simplessor/simplessor.github.io
          publish_branch: gh-pages
          destination_dir: reader
          keep_files: false
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: ${{ github.event.head_commit.message }}
      - name: Generate PreRelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body:
          draft: false
          prerelease: true
      - name: Upload Release Asset [.tar.gz]
        id: upload-release-asset-tar-gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: /tmp/book-reader-web.tar.gz
          asset_name: book-reader-web.tar.gz
          asset_content_type: application/zip
      - name: Upload Release Asset [.zip]
        id: upload-release-asset-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: /tmp/book-reader-web.zip
          asset_name: book-reader-web.zip
          asset_content_type: application/zip